packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  better-sqlite3: true
  "@prisma/client": false
  "@prisma/engines": true
  prisma: true
  esbuild: true
  sharp: true
  "@sentry/cli": true
  msgpackr-extract: true
  unrs-resolver: true
